Azure/iot-ux-fluent-controls

CHANGELOG.md
lib/components/DateTime/DateTimeField.md
lib/components/DateTime/DateTimeField.tsx
package.json

Initially, if DateTimeField recieived an empty string, it would incorrectly try to parse it into JSON causing browser error. This change allows the 'invalid' flag to be set when an empty string is passed, which causes the empty string to be set in the state.

Allowing DateTimeField to accept empty string

---

.npmignore
CHANGELOG.md
README.md
lib/common/_color.controls.scss
lib/components/Shell/Shell.scss
lib/scripts/postinstall.ts
package-lock.json
package.json
src/styles/_colors.scss
webpack.styleguide.js

The controls library previously depended on a global `colors` import, which would be resolved to an actual file through a webpack IncludePath declaration. This pattern meant we could not use the library with create-react-app unless we ejected, which is not optimal.
To avoid this, this PR changes the convention to depend on a `./src/styles/_colors.scss` file existing at the project root instead. This file is created as a postinstall step when the controls library is installed.

Remove webpack includePath dependency

---

package-lock.json
package.json

Remove nodemon and webpack-dev-server from package.json - they're not being used and are showing up in the npm audit.
We still have one high vulnerability coming from react-styleguidist > webpack-dev-server, but that requires updating to a new major version of styleguidist/webpack so leaving that for a different PR.

Remove high-vulnerability packages

---

CHANGELOG.md
lib/components/Field/FormField.spec.tsx
lib/components/Field/FormField.tsx
lib/components/List/GenericManagementList.tsx
package-lock.json
package.json

Fixed
- [BUG 3217787](): [Form Field] If the user tabs out of a field when the tooltip button is open (Alt+F1), close the tooltip.
- [BUG 2383275](https://msazure.visualstudio.com/One/_workitems/edit/2383275): [Management List] Narrator should not read non-interactive column headers as Buttons.

Fix accessibility issues

---

lib/components/ContextPanel/ContextPanel.md
lib/components/ContextPanel/ContextPanel.module.scss
lib/components/ContextPanel/ContextPanel.spec.tsx
lib/components/ContextPanel/ContextPanel.tsx
lib/components/ContextPanel/index.ts
lib/components/ContextPanel/portal.tsx
lib/components/ContextPanel/root.tsx
lib/components/Shell/Shell.module.scss
lib/components/Shell/Shell.tsx
lib/index.ts
styleguide.config.js

This PR adds a Context Panel (flyout in RM terms) to the Fluent Controls, since it's now a common shared component in the new design language intended for App Settings, Documentation etc. The styling is mostly the same as the ContentPanel that Vincenzo added as part of the new Masthead, but after last week's discussion, the design has been changed to be more generic so we can reuse the panel outside the Masthead as well.
Usage:
```tsx
<ContextPanel 
header='Hello'
footer={<Btn icon='cancel' onClick={()=> alert('cancel triggered')} attr={{ container: { autoFocus: true }}}>Cancel</Btn>}
onClose={()=> alert('cancel triggered')}
>
This is context panel 1          
</ContextPanel>
```
The ContextPanel takes in the following properties:
```ts
interface ContextPanelProperties {
onClose: …
```

Add Context Panel

---

CHANGELOG.md
lib/components/Input/SelectInput.module.scss
package.json

Fix line height of select input to avoid cutting text with browser zoom

---

lib/components/DateTime/DatePicker.tsx

In DatePicker, the button that triggers the calendar pop up has attribute aria-expanded. The text input does not trigger the pop up and is not very reasonable to have aria-expanded attribute although the bug says it should be fixed that way. The solution here removes combobox role for text input since the button and the text input are siblings in element level and it make more sense to me not to assign a combobox role for the text input.
Related task item: https://msazure.visualstudio.com/One/_workitems/edit/3858806

remove role for text input of date-picker

---

CHANGELOG.md
lib/components/ActionTrigger/ActionTrigger.module.scss
package-lock.json
package.json

Fixed the padding in action trigger items. This was showing an inconsistency in the hover of focused buttons because the outline would not completely dissapear.
**Before:**
Focused: ![7](https://user-images.githubusercontent.com/2132567/53529282-fcaec000-3aa0-11e9-9832-038b5d739d37.PNG)
Focused & Hover: ![8](https://user-images.githubusercontent.com/2132567/53529283-fcaec000-3aa0-11e9-9b32-75c08caf0703.PNG)
**After:**
Focused: ![5](https://user-images.githubusercontent.com/2132567/53529119-8c07a380-3aa0-11e9-89bd-a7838d82a886.PNG)
Focused & Hover: ![6](https://user-images.githubusercontent.com/2132567/53529120-8ca03a00-3aa0-11e9-8c67-48ca98bb33ef.PNG)
This bug only repros in Chrome and Edge, the fix works in both browsers and does not repro the UI of other browsers (in both Windows and …

Fix padding of action bar items

---

lib/components/ActionTrigger/ActionTrigger.tsx
lib/components/ActionTrigger/ActionTriggerButton.tsx
lib/components/Button/Button.tsx
lib/index.ts

Last PR removed `Styles.ts` but there were some references that we missed. This is mainly to fix the build of the package.

Remove references for non-existing file

---

CHANGELOG.md
lib/components/Field/Field.module.scss
lib/components/Field/FormLabel.tsx
package-lock.json
package.json

In the form field label the far side container should not appear if the far side is not there. Also, it should have it's own class so we can access it directly with the attr.

Give its own class to inner far side container

---

CHANGELOG.md
lib/components/ActionTrigger/ActionTrigger.module.scss
package-lock.json
package.json

There was an error with the previous commit that the rightIcon on the actionTriggerButton would appear below the other content. This PR fixes that by showing it in the right position.

Fix displaying the rightIcon on actiontiggerbutton correctly

---

CHANGELOG.md
lib/common/_mixins.scss
lib/components/ActionTrigger/ActionTrigger.module.scss
lib/components/Button/Button.module.scss
lib/components/Button/Button.tsx
lib/components/Icon/Icon.module.scss
package-lock.json
package.json

The alignment of some instances of button and actionTiggerButton was off because of the changes of the previous release. This PR fixes those by leveraging flex in the button.
They should look like this now:

Fix alignment of items inside button and action trigger button

---

CHANGELOG.md
lib/components/DateTime/DatePicker.tsx
lib/components/DateTime/DateTimeField.tsx
lib/components/Masthead/Masthead.tsx
package.json

When we remove the value entirely from the date field, the value being returned in 'invalid' which in a sense breaks the validation as it is not a date expected. Adding a fix to return the value as null in order to let validation succeed as a empty string in the date field is essentially right.

Fix DatePicker + DateTimeField to return null and set value to empty when the value is removed

---

lib/components/DateTime/DateField.tsx
lib/components/DateTime/TimeField.tsx
lib/components/Field/CheckboxField.tsx
lib/components/Field/ComboField.tsx
lib/components/Field/NumberField.tsx
lib/components/Field/RadioField.tsx
lib/components/Field/SelectField.tsx
lib/components/Field/TextAreaField.tsx
lib/components/Field/TextField.tsx
lib/components/Field/ToggleField.tsx
package-lock.json
package.json

The base `FormField` component has a `hideError` property that hides the default 20px FieldError. This property is not exposed in the wrapper TextField/DateField etc. components, so this PR exposes them.
This is required to show the TwinStatusField in ux-renderer correctly - it needs to show the twin syncing/synced status below the input (like a FieldError, but without the error colors). We need a way to stop showing the extra 20px error div in this case.

Add `hideError` property to all FormField properties

---

lib/components/Field/Field.module.scss
lib/components/GalleryCard/GalleryCard.module.scss
package-lock.json
package.json

1. Change FieldError's display from `inline-block` to `block` since it's not inline, and to avoid adding an extra 5px to the end of the FormField.
2. Add pointer:cursor to Link GalleryCard

Minor styling fixes

---

lib/components/Masthead/Masthead.module.scss
package-lock.json
package.json

The overall padding between masthead logo and masthead title should be 1rem according to design. Currently, it is greater than 1rem.

fixing padding for masthead title

---

CHANGELOG.md
lib/components/Balloon/Balloon.tsx
lib/components/DateTime/Calendar.tsx
lib/components/DateTime/DateField.tsx
lib/components/DateTime/DatePicker.tsx
lib/components/DateTime/DateTimeField.tsx
lib/components/DateTime/TimeInput.tsx
lib/components/Input/NumberInput.tsx
lib/components/Navigation/Navigation.tsx
package-lock.json
package.json

- Change `data-active` attribute to be a boolean attribute (i.e., emit \<foo data-active> instead of \<foo data-active="true">)
- Rename componentWillReceiveProps to [UNSAFE_componentWillReceiveProps](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) to avoid deprecation warnings in React 16.11+
- Add deprecation warnings for Date components because they're not fully localized/accessible. We should use the [Office Fabric control](https://developer.microsoft.com/en-us/fabric/#/controls/web/datepicker) instead.
- Update handlebars version to fix vulnerability

Fix deprecation warnings

---

CHANGELOG.md
lib/components/Thumbnail/Thumbnail.tsx
package-lock.json
package.json

Allows for `attr.container` and `attr.img` to be properly applied to the corresponding elements.

Fix thumbnail attr

---

lib/components/Masthead/Masthead.module.scss

Masthead logo was updated with one of the previous checkins and this css to center vertically the logo was missing.

Update masthead to center logo

---

lib/components/Button/Button.module.scss

The focus state for default buttons was not properly set, making it so that it was really hard to see. This updates it so it's the same as the danger and primary buttons.

Fix focus indicator to show on default buttons on focus

---

lib/components/Field/FormLabel.tsx

Fixes an accessibility issue to add name to the icon that opens the balloon in form field labels.

Add name to balloon info icon

---

lib/components/Field/FormError.tsx
lib/components/Field/FormField.tsx

Added aria label to the error icon on formError, this will make it so that any screen reader will announce this label before announcing the actual error message, giving more context to the user that the text they will hear is an error. 
This is added as a prop to allow internationalization.

Add error aria label to form error icon

---

lib/components/Balloon/Balloon.tsx
lib/components/DateTime/DateField.tsx
lib/components/DateTime/DateTimeField.tsx
lib/components/Dropdown/Dropdown.module.scss
lib/components/Dropdown/Dropdown.tsx
lib/components/Field/CheckboxField.tsx
lib/components/Field/ComboField.tsx
lib/components/Field/FormLabel.tsx
lib/components/Field/NumberField.tsx
lib/components/Field/RadioField.tsx
lib/components/Field/SelectField.tsx
lib/components/Field/TextAreaField.tsx
lib/components/Field/TextField.tsx
lib/components/Field/ToggleField.tsx
lib/components/Input/ComboInput.tsx
lib/components/Shell/Shell.tsx

The dropdown component was updated to use a React.Portal, because of the way aria live regions works this made it so that the announcement of tooltip text was not being done.
I also noticed that the portal was not actually used as a portal, so I removed it and made the container a live region, so that screen readers announce any changes to that container, therefore announce the tooltip when open.

Make screen readers announce balloon tooltips

---

lib/components/DateTime/DateField.tsx
lib/components/Field/CheckboxField.tsx
lib/components/Field/ComboField.tsx
lib/components/Field/RadioField.tsx
lib/components/Field/SelectField.tsx
lib/components/Field/TextAreaField.tsx
lib/components/Field/TextField.tsx
lib/components/Field/ToggleField.tsx

Add missing errorAriaLabel to all fields to use new error aria label in the formField

Add errorAriaLabel to all fields

---

CHANGELOG.md
lib/components/DateTime/DateField.tsx
lib/components/DateTime/DateTimeField.tsx
lib/components/Field/TextField.tsx
package-lock.json
package.json

No two `id`s on a page should be the same ([duplicate-id-aria](https://dequeuniversity.com/rules/axe/3.3/duplicate-id-aria?application=msftAI)).
If you have a DateField/DateTimeField/TextField with the same `props.name` then this error will arise.
This PR ensures that no two components will have the same ID.

Add instanceCount to ensure unique IDs (ARIA)

---

CHANGELOG.md
lib/components/ActionTrigger/ActionTrigger.tsx
lib/components/ActionTrigger/ActionTriggerButton.tsx
package-lock.json
package.json

This allows us to pass in Fabric's `Icon` component into `ActionTriggerButton`s

Allow icon prop in ActionTrigger to be ReactNode

---

CHANGELOG.md
lib/components/Navigation/Navigation.module.scss
lib/components/Toggle/Toggle.module.scss
package-lock.json
package.json

Bug fixes for two issues:
- Toggle outline was not correct because the size of the component didn't match the other input components and the left side was hidden if there was no space (margin or padding) in the component.
- Navigation focus would hide the right outline of a navigation item when collapsed.
Before:
After:

Fixes a couple of styling issues

---

lib/components/Field/ToggleField.tsx
lib/components/Toggle/Toggle.tsx

Toggle input component was reusing the `container` attr twice, this is a mistake since every component should have it's own attr reference.

Fix wrongly used attr

---

lib/components/Icon/Icon.module.scss
lib/components/Icon/Icon.tsx
lib/components/Masthead/Masthead.tsx
lib/components/SearchInput/SearchInput.tsx

Icons sizes where being set on the `.icon-${size} .icon-${size}:before`, since we don't have any nested `icon-${size}` elements in our DOM it was (since always) being ignore, this made every icon just constraint to the size of the icon symbol itself (in most cases around 14 pixels height and auto width).
With this change the icons will actually take our sizes into account.
This PR also cleans up the icon component and wrapps it in a memo.

Fix icon sizing to actually constraint icons

---

lib/components/Input/CheckboxInput.module.scss

Cleanup css for checkbox component to make easy transition to new colors pattern.
This change should not change any current styles, it just cleans up the code and makes sure there is consistency between the experience of the checkbox states

Cleanup checkbox css

---

lib/common/_constants.scss
lib/components/Alert/Alert.module.scss
lib/components/Masthead/Masthead.module.scss
lib/components/Masthead/Masthead.tsx
lib/components/SearchInput/SearchInput.module.scss
lib/components/Toggle/Toggle.tsx

Masthead now uses React.memo and the css is cleaned up to remove unnecessary rules.

Refactor masthead to use memo and fix styling

---

CHANGELOG.md
lib/components/GalleryCard/GalleryCard.module.scss
lib/components/GalleryCard/SolidBackground.tsx
package-lock.json
package.json

There are a couple of places in renderer that the gallery card is used passing a hardcoded `'blue'` color. This is the only component where we use "blue" as a color instead of using our accent color (which is blue).
Using the hardcoded 'blue' makes this component not respond correctly to white labeling, therefore this PR aims to change it to use `primary` instead and use the correct CSS custom property for coloring.
The user of this component can still pass in a className to provide a custom color if needed, therefore all the current behavior is kept as is.

Update gallery card solid background to not accept hardcoded colors

---

lib/components/Loader/HorizontalLoader.module.scss
lib/components/Loader/Spinner.module.scss

Align loading indicators to use the accent color as the progress indicators in central.

Make progress use accent color

---

lib/components/Input/CheckboxInput.module.scss

If we update the foreground when hovering depending on the user's accent color we might have a foreground that is not really visible. Updating the background to an appropriate accent shade is the correct way to avoid this.

Update checkbox selected/indetermine background when hover instead of foreground

---

lib/components/Input/TextInput.module.scss

The text input element should have consistent paddings everywhere to avoid jumpiness when focusing or removing focus.
Input default state:
Input focus state:
Note that the padding should be the exact same in both states

Fix padding on input field to avoid jumpiness on focus

---

CHANGELOG.md
lib/components/SearchInput/SearchInput.module.scss
package-lock.json
package.json

In an effort to make white labeled more accessible in every possible masthead color selection it was decided to add a dropshadow to the search bar to make it have more contrast to the masthead background.
This follows the practice that office uses on their search bar and here are some examples of how it looks on different backgrounds:

Add drop-shadow to search bar
