Azure/iot-ux-fluent-controls

lib/components/Masthead/Masthead.module.scss, lib/components/Masthead/Masthead.tsx, lib/components/Masthead/MastheadToolbar.tsx, lib/components/Navigation/Navigation.module.scss, lib/components/Navigation/Navigation.tsx, lib/components/Shell/Shell.module.scss, lib/components/Shell/Shell.tsx, package-lock.json, package.json
With the new UI alignment, we need to have masthead and global nav integrated into shell.
=> [UI Alignment] Support new Global Nav

lib/components/ActionTrigger/ActionTrigger.module.scss, lib/components/ActionTrigger/ActionTriggerButton.tsx, lib/components/ContextPanel/ContextPanel.tsx, lib/components/Input/TextInput.tsx, lib/components/Masthead/Masthead.module.scss, lib/components/Masthead/Masthead.spec.tsx, lib/components/Masthead/Masthead.tsx, lib/components/Masthead/index.ts, lib/components/Navigation/index.ts, lib/components/SearchInput/SearchInput.spec.tsx, lib/components/SearchInput/SearchInput.tsx, lib/components/Shell/Shell.tsx, lib/components/Thumbnail/Thumbnail.tsx, lib/index.ts, package-lock.json, package.json
This PR contains various bugfixes discovered when updating iotcentral to the uialignment branch
=> Minor uialignment bugfixes

CHANGELOG.md, lib/components/Masthead/Masthead.module.scss, lib/components/Shell/Shell.tsx, package-lock.json, package.json
- Masthead user display name and email are now centered vertically.
- Shell now allows Masthead to use a different NavigationProperties than the one passed to the main navbar.
=> More uialignment fixes

CHANGELOG.md, package.json
This pull request is to add version information for this [merge](https://github.com/Azure/iot-ux-fluent-controls/pull/63) in order to create a version release.
=> update version for bug(3858806) fixing

CHANGELOG.md, lib/Styled.ts, lib/components/ActionTrigger/ActionTrigger.module.scss, lib/components/ActionTrigger/ActionTrigger.tsx, lib/components/ActionTrigger/ActionTriggerButton.tsx, lib/components/Button/Button.tsx, lib/components/List/GenericManagementList.tsx, lib/components/Masthead/Masthead.module.scss, lib/components/Masthead/Masthead.spec.tsx, lib/components/Masthead/Masthead.tsx, lib/components/Shell/Shell.tsx, lib/index.ts, package-lock.json, package.json
- add logo slot to Masthead component
- update Masthead, ActionTriggerButton, Button to support required theme customization.
=> fluent library change to support white labeling

CHANGELOG.md, lib/components/DateTime/DateField.tsx, lib/components/DateTime/DateTimeField.tsx, lib/components/DateTime/TimeField.tsx, lib/components/Field/CheckboxField.tsx, lib/components/Field/ComboField.tsx, lib/components/Field/Field.module.scss, lib/components/Field/FormField.tsx, lib/components/Field/FormLabel.tsx, lib/components/Field/NumberField.tsx, lib/components/Field/RadioField.tsx, lib/components/Field/SelectField.tsx, lib/components/Field/TextAreaField.tsx, lib/components/Field/TextField.tsx, lib/components/Field/ToggleField.tsx, package-lock.json, package.json
Added the ability for the consumer to specify an extra node to be added at the far side of the label in form fields.
e.g. Adding an ActionTriggerButton:
=> Add extra action node to form field

CHANGELOG.md, lib/components/Input/CheckboxInput.tsx, lib/components/Toggle/Toggle.module.scss, lib/components/Toggle/Toggle.tsx, package-lock.json, package.json
- BUG 4640169: White Accent setting causing problem in all the checkbox
- Fix hover styles for toggle input
=> Fix styling bugs in Checkbox and Toggle 

CHANGELOG.md, lib/components/ActionTrigger/ActionTrigger.module.scss, lib/components/Button/Button.module.scss, lib/components/Button/Button.tsx, lib/components/DateTime/DatePicker.module.scss, lib/components/Icon/Icon.module.scss, package-lock.json, package.json
Fixes bugs 4777715 and 4776574 ... 
Previous alignment:
Alignment with changes in this PR:
=> Fix alignment of icons in buttons

lib/common/_color.controls.scss, lib/common/_constants.scss, lib/common/_icons.scss, lib/components/List/GenericManagementList.module.scss, lib/components/Masthead/Masthead.module.scss, lib/components/Masthead/Masthead.tsx, lib/components/Navigation/Navigation.module.scss, lib/components/Shell/Shell.module.scss, lib/components/Shell/Shell.tsx, package-lock.json, package.json
This is the first step in the migration to the new colors in the fluent control library.
=> Adopt new CSS library version and migrate shell, masthead and navigation to CSS custom properties

lib/components/Toggle/Toggle.tsx, package-lock.json, package.json
Bug fix https://msazure.visualstudio.com/One/_workitems/edit/5553910
=> [ToggleField] stop render whilte label colors when control is disabled

lib/components/Field/TextAreaField.tsx, lib/components/Field/TextField.tsx, lib/components/Input/ComboInput.tsx, lib/components/Input/TextArea.tsx, lib/components/Input/TextInput.tsx
This will allow us to plumb in the formik blur event into fields and only show errors for fields that have been touched.
=> Add onBlur handlers for TextInput/TextArea

lib/components/Thumbnail/Thumbnail.module.scss, package-lock.json, package.json
=> Adds border to thumbnail component for device icon continuity

lib/components/Navigation/Navigation.module.scss, package-lock.json, package.json
1. Changes width of `top-container` to be correct when navbar is collapsed
=> Fix width of nav items when nav is collapsed

lib/components/Balloon/Balloon.module.scss, lib/components/Balloon/Balloon.tsx, lib/components/Dropdown/Dropdown.module.scss, lib/components/Dropdown/Dropdown.tsx, lib/components/Field/ComboField.tsx, lib/components/Field/Field.module.scss, lib/components/Field/FormField.tsx, lib/components/Field/FormLabel.tsx, lib/components/Input/ComboInput.tsx, lib/components/Shell/Shell.tsx
Fix styling on balloon to have correct gutters and rewrite dropdown to not use unsupported react methods and support start/end alignment
=> Fix ballon styles and allow it to align itself to the end

.vscode/settings.json, CHANGELOG.md, lib/Attributes.ts, lib/components/ContextPanel/ContextPanel.module.scss, lib/components/ContextPanel/ContextPanel.tsx, lib/components/Masthead/Masthead.module.scss, lib/components/Navigation/Navigation.module.scss, lib/components/Shell/Shell.module.scss, lib/components/Shell/Shell.tsx, package-lock.json, package.json
- Removed RTL references from shell since now the CSS library handles it.
- Update positions and sizes of main shell and workspace DOM elements
- Updated ContextPanel to have a correct layout
=> Update RTL to not be dependant on a class and update layout in shell

CHANGELOG.md, lib/components/Loader/HorizontalLoader.tsx, package-lock.json, package.json
Adding data-test-hook for HorizontalLoader so that we can detect loading states in E2E tests.
=> Adding data-test-hook for HorizontalLoader

CHANGELOG.md, lib/components/Input/RadioInput.module.scss, package.json
Update radio input style to align to checkbox input
=> Update radio input style

lib/components/ActionTrigger/ActionTrigger.tsx, lib/components/ActionTrigger/ActionTriggerButton.tsx, lib/components/ActionTrigger/ActionTriggerLink.tsx, lib/components/Alert/Alert.tsx, lib/components/Button/Button.tsx, lib/components/ContextPanel/ContextPanel.tsx, lib/components/Field/ToggleField.tsx, lib/components/GalleryCard/GalleryCard.tsx, lib/components/GalleryCard/ImageBackground.tsx, lib/components/GalleryCard/SolidBackground.tsx, lib/components/Icon/IconBackground.tsx, lib/components/Input/CheckboxInput.tsx, lib/components/List/GenericManagementList.tsx, lib/components/List/ManagementList.tsx, lib/components/Loader/HorizontalLoader.tsx, lib/components/Loader/Spinner.tsx, lib/components/Navigation/Navigation.tsx, lib/components/Pivot/PivotMenu.tsx, lib/components/SearchInput/SearchInput.tsx, lib/components/Thumbnail/Thumbnail.tsx
Some components were easy wins to add React.memo and get better performance without changing a lot of the structure of the code. Also took the chance to cleanup a bit of the code in some places, removing defaults components and moving to hooks.
=> Cleanup code and add memo to some components

lib/components/ActionTrigger/ActionTrigger.spec.tsx, lib/components/ContextPanel/ContextPanel.spec.tsx, lib/components/DateTime/DatePicker.spec.tsx, lib/components/Input/CheckboxInput.spec.tsx, lib/components/Input/CheckboxInput.tsx, lib/components/Input/NumberInput.spec.tsx, lib/components/Masthead/Masthead.spec.tsx, lib/components/SearchInput/SearchInput.spec.tsx, lib/components/Thumbnail/Thumbnail.tsx, package-lock.json
Fixing some missing null checks that went in the last check in and updating the highly vulnerable packages
=> Fix build and update vulnerable packages

lib/components/Toggle/Toggle.module.scss, lib/components/Toggle/Toggle.tsx
Accessibility fix for the toggle to keep focus after it is clicked (with mouse or keyboard)
=> Fix toggle to keep focus after click

lib/components/Field/FormLabel.tsx
This reverts commit d5c8973ee0a47ac28b5a679a87191926982f7b4f.
=> Revert "Add name to balloon info icon (#162)"

lib/components/Balloon/Balloon.tsx, lib/components/DateTime/Calendar.tsx, lib/components/DateTime/DatePicker.tsx, lib/components/DateTime/DateTimeField.tsx, lib/components/DateTime/TimeInput.tsx, lib/components/Input/NumberInput.tsx
Balloon, number and date components were using unsafe methods... This PR aims to remove them by moving the logic they had to use hooks. This is a step forward towards react concurrent mode.
=> Refactor components to not use unsafe react methods

CHANGELOG.md, lib/components/Balloon/Balloon.tsx, lib/components/DateTime/DatePicker.tsx, lib/components/DateTime/TimeInput.tsx, lib/components/Dropdown/Dropdown.module.scss, lib/components/Dropdown/Dropdown.tsx, lib/components/Field/FormLabel.tsx, lib/components/Masthead/Masthead.tsx, lib/components/Shell/Shell.tsx, package-lock.json, package.json
This PR fixes the random `md-dropdown-container` div blocking parts of the screen.
This same fix also fixes the tutorial not being able to click, the tutorial moving around, the admin page crashing on SSR, and the color picker crash.
=> Fix random div blocking screen

CHANGELOG.md, lib/components/Input/TextInput.module.scss, lib/components/Navigation/Navigation.tsx, package-lock.json, package.json
Fabric updated their command bar from 40 to 44px (https://github.com/OfficeDev/office-ui-fabric-react/commit/cf893d1feebb868ae07e96e7c476b361b953fc5a#diff-67b0ecc6b3d15d4195d7b2a36b12f8a2R3) we have to change our nav items to make our layouts align properly. CSS library update addresses this too.
Also fixed an issue with the text input icon not properly showing.
=> Update nav item height and fix text input cancel icon

CHANGELOG.md, lib/components/Dropdown/Dropdown.module.scss, lib/components/Shell/Shell.module.scss, package-lock.json, package.json
=> Fix text color on tooltip

lib/components/Alert/Alert.module.scss
Alert CSS had some unnecessary repetition of code, this PR doesn't affect styling just cleans up the css code.
=> Cleanup styles for alert control

CHANGELOG.md, lib/components/Input/TextInput.module.scss, lib/components/Shell/Shell.module.scss, package-lock.json, package.json
Updated the version of css library that brings in some new link colors and updated the usage of them in this library.
Also fixed an issue with input where the placeholder was not updated with disabled styles.
=> Update css library and minor style fixes

CHANGELOG.md, lib/components/Field/FormField.tsx, package-lock.json, package.json
If a form field doesn't have an error, we're currently setting its title to `false`, which triggers a react warning "Received `false` for a non-boolean attribute `title`".
Set title to undefined if the error property isn't a string.
=> Fix react warning "Received `false` for a non-boolean attribute `title`"
